version: "3.9"
    
services:
  db:
    image: tagost/mysql
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
      #environment:
      #POSTGRES_PASSWORD: 123456
      #POSTGRES_DB: postgres
      #POSTGRES_USER: postgres
    
  admin-php:
    depends_on:
      - db
    build: .
    image: tagost/admin-php:fpm-nginx
    container_name: admin
    #volumes:
     # - wordpress_data:/var/www/html
    ports:
      - "9000:8080"
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: crud_2019
      DB_USER: root
      DB_USER_PASSWORD: root
volumes:
  db_data: {}
