version: "3.9"
    
services:
  db:
    image: tagost/mysql
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
      #environment:
      #POSTGRES_PASSWORD: 123456
      #POSTGRES_DB: postgres
      #POSTGRES_USER: postgres
    
  admin-php:
    depends_on:
      - db
    image: tagost/admin-php
    container_name: admin
    #volumes:
     # - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
      #environment:
      #DB_HOST: db
      #DB_PORT: 5432
      #DB_NAME: postgres
      #DB_USER: postgres
      #DB_USER_PASSWORD: 123456
volumes:
  db_data: {}
